import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const normalizeBaseUrl = (value) => (value || '').trim().replace(/\/+$/, '');
const parseBaseUrls = (value) =>
  String(value || '')
    .split(/[,;\s]+/)
    .map(normalizeBaseUrl)
    .filter(Boolean);

const apiBaseUrl = normalizeBaseUrl(
  process.env.PINEGUARD_API_BASE_URL || 'https://pineguard-api.onrender.com',
);
const additionalApiBaseUrls = parseBaseUrls(
  process.env.PINEGUARD_ADDITIONAL_API_BASE_URLS || '',
);
const apiBaseUrls = [
  ...new Set([apiBaseUrl, ...additionalApiBaseUrls].filter(Boolean)),
];

if (!apiBaseUrl) {
  throw new Error('PINEGUARD_API_BASE_URL is required for the Web Admin build.');
}

const configPath = resolve('web_admin', 'pineguard-api-config.js');
const config = `// Generated by deploy/render_write_web_config.mjs.
window.PINEGUARD_API_BASE_URL = ${JSON.stringify(apiBaseUrl)};
window.PINEGUARD_API_BASE_URLS = ${JSON.stringify(apiBaseUrls)};
window.PINEGUARD_ENABLE_LOCAL_API_DISCOVERY = false;
`;

writeFileSync(configPath, config);
console.log(`Wrote ${configPath} -> ${apiBaseUrls.join(', ')}`);
